//! Goldberg-family `steam_settings/` config generation.

use crate::EmulatorFlavor;

/// Runtime configuration written into `<game_dir>/steam_settings/`.
///
/// File names follow the layouts parsed by `settings_parser.cpp` in both
/// gbe_fork and gse_fork (see docs/research/COMPARATIVE_ANALYSIS.md).
#[derive(Debug)]
pub struct SteamSettings {
    pub app_id: u32,
    /// One address per line → `custom_broadcasts.txt`.
    pub custom_broadcasts: Vec<String>,
    /// Interface list → `steam_interfaces.txt` (generated by `generate_interfaces`).
    pub interfaces: Vec<String>,
}

impl SteamSettings {
    pub fn render_custom_broadcasts(&self) -> String {
        self.custom_broadcasts.join("\n")
    }

    pub fn render_steam_appid(&self) -> String {
        self.app_id.to_string()
    }

    pub fn render_steam_interfaces(&self) -> String {
        self.interfaces.join("\n")
    }

    pub fn flavor(&self) -> EmulatorFlavor {
        // Placeholder until per-flavor INI templating lands (configs.main.ini).
        EmulatorFlavor::GbeFork
    }
}
